import { readFile, mkdir, writeFile, cp } from 'node:fs/promises';
const data = JSON.parse(await readFile(new URL('../content.json', import.meta.url), 'utf8'));
const output = new URL('../dist/', import.meta.url);
await mkdir(output, { recursive: true });
await cp(new URL('../assets/', import.meta.url), new URL('assets/', output), { recursive: true });
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const external = (url, label, cls = '') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}<span aria-hidden="true"> ↗</span><span class="sr-only"> (opens in a new tab)</span></a>`;
const confidentiality = 'Some implementation details and source code are not publicly available because these projects were developed as part of my professional work.';
const resume = prefix => data.resume ? `<a class="button secondary" href="${prefix}assets/${esc(data.resume)}" download>Download Resume <span aria-hidden="true">↓</span></a>` : '<span class="button secondary unavailable" aria-disabled="true">Resume coming soon</span>';
function layout({ title, description, path = '', body, detail = false }) {
 const prefix = detail ? '../' : './';
 const home = detail ? '../index.html' : '';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#172b2a"><link rel="canonical" href="${data.origin}/${path}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${data.origin}/${path}"><meta property="og:site_name" content="Enoch Benson"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" href="${prefix}assets/favicon.svg"><link rel="stylesheet" href="${prefix}assets/style.css"><script src="${prefix}assets/main.js" defer></script></head><body>
 <a class="skip" href="#main">Skip to content</a><header class="header"><div class="container header-inner"><a class="brand" href="${detail ? '../index.html' : '#'}" aria-label="Enoch Benson home"><span class="monogram">eb<span>.</span></span><span class="brand-name">Enoch Benson</span></a><button class="menu-toggle" type="button" aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation"><a href="${home}#work">Work</a><a href="${home}#approach">Approach</a><a href="${home}#experience">Experience</a><a href="${home}#about">About</a><a class="nav-contact" href="${home}#contact">Let’s talk <span aria-hidden="true">↗</span></a></nav></div></header>
 <main id="main">${body}</main><footer><div class="container footer-inner"><a class="brand" href="${detail ? '../index.html' : '#'}"><span class="monogram">eb<span>.</span></span><span>Enoch Benson</span></a><p>Built with care. Focused on what works.</p><a href="${home}#contact">Get in touch ↗</a></div></footer></body></html>`;
}
function visual(project, prefix = './', hero = false) {
 if (project.image) return `<div class="preview ${project.color} ${project.slug === 'nalerts' ? 'phone-preview' : ''} ${hero ? 'detail-preview' : ''}"><div class="preview-label"><span>${project.name}</span><span>${project.slug === 'nalerts' ? 'MOBILE APPLICATION' : 'PUBLIC WEBSITE'}</span></div><div class="browser-frame"><div class="browser-top"><i></i><i></i><i></i><span>${new URL(project.url).hostname}</span></div><img src="${prefix}assets/${project.image}" alt="${esc(project.imageAlt)}" width="${project.slug === 'nalerts' ? 720 : 1440}" height="${project.slug === 'nalerts' ? 1469 : project.slug === 'nfec' ? 9333 : 4791}" ${hero ? '' : 'loading="lazy"'} decoding="async"></div></div>`;
 if (project.personal) return `<div class="preview purple concept-preview"><div class="preview-label"><span>PERSONAL PRODUCT</span><span>IN DEVELOPMENT</span></div><div class="bant-mark">bant<span>✳</span></div><p>Good conversations.<br>Shared campus.</p><div class="concept-tags"><span>Voice rooms</span><span>Student communities</span></div><small>Product concept · MVP in development</small></div>`;
 return `<div class="preview green concept-preview"><div class="preview-label"><span>PROFESSIONAL WORK</span><span>DATA & SYSTEMS</span></div><div class="repository-mark" aria-hidden="true"><span></span><span></span><span></span></div><h3>NFDRC</h3><p>National Fire Data<br>Repository Center</p><small>Project overview · Public screenshot unavailable</small></div>`;
}
const services = [
 ['01','Build','Web and mobile applications, APIs and backend systems.'],
 ['02','Troubleshoot','Investigate technical problems, identify root causes and implement fixes.'],
 ['03','Test & Improve','Testing, debugging, validation and continuous system improvements.'],
 ['04','Data & Systems','Databases, dashboards, administrative systems and data workflows.'],
 ['05','Integrations','Payments, notifications, authentication and third-party services.'],
 ['06','Support & Operations','Technical support, system maintenance and helping people work with software.']
];
const steps = [['Understand','Clarify the problem, the people affected and the expected behaviour.'],['Investigate','Trace the issue through the application, API, database or workflow.'],['Learn','When something is unfamiliar, learn what is needed to move forward.'],['Solve','Build or fix the part of the system that addresses the root cause.'],['Test','Validate the solution and check the workflows around it.'],['Improve','Refine the system and address issues discovered through use.']];
const skills = [
 ['Languages & Web',['HTML','CSS','JavaScript','PHP','Python']],
 ['Development',['Full-stack development','Web development','UI/UX']],
 ['Mobile',['Mobile app development','Location-based workflows','Mobile notifications']],
 ['Backend & APIs',['Backend development','API development','Authentication','Role-based access control']],
 ['Databases & Systems',['Databases','Data management','Dashboards','Admin portals','Reporting systems']],
 ['Testing & Troubleshooting',['Testing','Debugging','Technical troubleshooting','Deployment']],
 ['Integrations',['Paystack','Firebase Cloud Messaging','Third-party services']],
 ['Professional',['Problem solving','Independent execution','English communication','Emotional intelligence']]
];
const card = p => `<article class="project-card">${visual(p)}<div class="project-content"><div class="eyebrow">${esc(p.category)}</div><h3>${p.name}${p.personal ? '<span class="development">In Development</span>' : ''}</h3><p>${p.summary}</p><p class="project-role"><span>My role</span>${p.role}</p><div class="project-links"><a href="case-studies/${p.slug}.html">View Case Study <span aria-hidden="true">→</span></a>${external(p.url, 'Visit Project')}</div></div></article>`;
const homeBody = `
 <section class="hero container" aria-labelledby="hero-title"><div class="hero-copy"><div class="availability"><span></span> Open to Remote Opportunities</div><p class="eyebrow intro-name">ENOCH BENSON · ABUJA, NIGERIA</p><h1 id="hero-title">Full-Stack Developer<br><em>&amp; Technical<br>Problem Solver.</em></h1><p class="hero-description">I build, troubleshoot, test and improve real-world digital systems — from mobile applications and APIs to databases, dashboards and administrative platforms.</p><div class="hero-buttons"><a class="button primary" href="#work">View My Work <span aria-hidden="true">↗</span></a>${resume('./')}<a class="text-button" href="#contact">Contact Me →</a></div><p class="hero-note"><span class="small-line"></span> Professional experience at 2TOC Solutions Ltd since 2020.</p></div>
 <aside class="hero-aside" aria-label="Professional focus"><div class="aside-top"><span>THE WORK BEHIND THE TITLE</span><span aria-hidden="true">↗</span></div><div class="aside-core"><span class="asterisk" aria-hidden="true">✳</span><p>Real systems.<br>Real responsibility.</p><span class="aside-text">From understanding the problem<br>to making the solution work.</span></div><div class="focus-row"><span>01</span><p>Build & integrate</p><span aria-hidden="true">↗</span></div><div class="focus-row"><span>02</span><p>Investigate & resolve</p><span aria-hidden="true">↗</span></div><div class="focus-row"><span>03</span><p>Test & keep improving</p><span aria-hidden="true">↗</span></div><div class="aside-bottom"><span>FULL-STACK · MOBILE · SUPPORT · DATA</span></div></aside></section>
 <div class="domain-strip"><div class="container"><span>EXPERIENCE ACROSS</span><p>Public safety</p><i></i><p>Emergency response</p><i></i><p>Fire safety</p><i></i><p>Data management</p></div></div>
 <section class="section container" id="what-i-do"><div class="section-heading"><div><p class="eyebrow">01 / WHAT I DO</p><h2>Useful across the<br>whole system.</h2></div><p>Development is part of the job. So is understanding what broke, helping people use the software and keeping it working.</p></div><div class="services">${services.map(([num,name,text])=>`<article class="service"><span class="service-number">${num} <span aria-hidden="true">↗</span></span><h3>${name}</h3><p>${text}</p></article>`).join('')}</div></section>
 <section class="section work-section" id="work"><div class="container"><div class="section-heading"><div><p class="eyebrow">02 / SELECTED WORK</p><h2>Systems I’ve<br>helped move forward.</h2></div><p>Professional work across public-sector digital platforms, alongside a product I’m developing of my own.</p></div><div class="project-grid">${data.projects.map(card).join('')}</div><p class="confidentiality"><span aria-hidden="true">↳</span> ${confidentiality} Company branding and project assets belong to their respective owners.</p></div></section>
 <section class="section approach-section" id="approach"><div class="container"><div class="section-heading"><div><p class="eyebrow">03 / HOW I APPROACH PROBLEMS</p><h2>I don’t just write code.<br><em>I take responsibility.</em></h2></div><p>A practical, self-directed approach: understand the issue, follow the evidence and deliver a solution that works.</p></div><div class="steps">${steps.map(([name,text],i)=>`<article><div class="step-top"><span>0${i+1}</span><span aria-hidden="true">${i===5?'✓':'→'}</span></div><h3>${name}</h3><p>${text}</p></article>`).join('')}</div></div></section>
 <section class="section container" id="experience"><div class="section-heading"><div><p class="eyebrow">04 / EXPERIENCE</p><h2>More scope.<br>More ownership.</h2></div><p>My progression at 2TOC Solutions Ltd — from mobile application development to broader technical delivery.</p></div><div class="experience-row"><div class="experience-meta"><p>2025 — Present</p><span>2TOC Solutions Ltd<br>Abuja, Nigeria</span></div><div><h3>Sole Developer /<br>Full-Stack Technical Lead</h3><p>Promoted from mobile app development into broader ownership of product development and technical delivery.</p><ul><li>Work across security, emergency response, fire safety and national data-management systems.</li><li>Contribute to mobile apps, dashboards, admin portals, APIs, databases and backend systems.</li><li>Work across UI/UX, backend logic, database design, testing, debugging, deployment support and continuous upgrades.</li></ul></div></div><div class="experience-row"><div class="experience-meta"><p>2020 — 2024</p><span>2TOC Solutions Ltd<br>Abuja, Nigeria</span></div><div><h3>Mobile App Developer</h3><p>Developed and maintained mobile applications with registration, emergency reporting, location-based support and communication workflows.</p><p>Worked on application updates, testing, feature improvements and technical troubleshooting.</p></div></div></section>
 <section class="section skills-section" id="skills"><div class="container"><div class="section-heading"><div><p class="eyebrow">05 / SKILLS & CAPABILITIES</p><h2>A broad technical<br>toolkit. A practical focus.</h2></div><p>The tools and capabilities I bring to building, supporting and improving applications.</p></div><div class="skills-grid">${skills.map(([name,items])=>`<article><h3>${name}</h3><div class="tags">${items.map(item=>`<span>${item}</span>`).join('')}</div></article>`).join('')}</div></div></section>
 <section class="section container about-section" id="about"><div><p class="eyebrow">06 / ABOUT ME</p><h2>A problem solver,<br>before anything else.</h2></div><div class="about-copy"><p class="large-copy">I’m Enoch, a full-stack and mobile developer based in Abuja, Nigeria. I’ve worked hands-on with real production systems — and the everyday work of building, testing, maintaining and improving them.</p><p>I’m comfortable taking a problem from requirements through investigation, development, testing and deployment. When I encounter something unfamiliar, I learn what I need and work toward a practical solution with minimal supervision.</p><p>I value clear English communication, thoughtful collaboration and understanding the people behind a technical issue. I’m currently completing university and open to remote opportunities.</p><div class="role-fit"><span>OPEN TO ROLES IN</span><p>Full-stack development · Application & software support · Technical support · Implementation · QA & UAT testing · Technical operations · Systems analysis · Data & systems</p></div></div></section>
 <section class="contact-section" id="contact"><div class="container"><div class="availability"><span></span> Open to Remote Opportunities</div><div class="contact-heading"><div><p class="eyebrow">07 / LET’S CONNECT</p><h2>Have a system to build.<br>Or a problem to solve?</h2><p>I’d welcome a conversation about your team, your software and where I can contribute.</p></div><a class="contact-arrow" href="mailto:${esc(data.email)}" aria-label="Email Enoch Benson">↗</a></div><div class="contact-links"><a href="mailto:${esc(data.email)}"><span>EMAIL</span>${esc(data.email)} ↗</a>${data.linkedin ? external(data.linkedin,'<span>LINKEDIN</span>Enoch Benson') : '<span>LinkedIn — available on request</span>'}${external(data.github,'<span>GITHUB</span>Tireni')}<div><span>RESUME</span>${resume('./')}</div></div></div></section>`;
await writeFile(new URL('index.html', output), layout({ title: 'Enoch Benson | Full-Stack Developer & Technical Problem Solver', description: 'Enoch Benson builds, troubleshoots, tests and improves real-world digital systems. Explore professional case studies, experience and remote work availability.', body: homeBody }));
await mkdir(new URL('case-studies/', output), { recursive: true });
for (const project of data.projects) {
 const items = values => `<ul>${values.map(value=>`<li>${esc(value)}</li>`).join('')}</ul>`;
 const body = `<section class="container case-hero"><a class="back-link" href="../index.html#work">← Back to selected work</a><p class="eyebrow">${esc(project.category)} · ${project.personal ? 'OWN PRODUCT' : 'PROFESSIONAL CASE STUDY'}</p><h1>${project.name}<span>${project.subtitle}</span></h1><p class="case-summary">${project.summary}</p><div class="case-meta"><div><span>MY ROLE</span><p>${project.role}</p></div><div><span>OWNERSHIP</span><p>${project.personal ? 'Personal product · In Development' : 'Professional work · 2TOC Solutions Ltd'}</p></div><div>${external(project.url,'Visit Public Project','button primary')}</div></div></section><div class="container case-visual">${visual(project,'../',true)}</div><section class="container case-body"><aside class="case-index"><p class="eyebrow">IN THIS CASE STUDY</p>${[['overview','Overview'],['problem','Problem'],['my-role','My Role'],['work','What I Worked On'],['functionality','Key Functionality'],['challenges','Challenges'],['approach','Approach'],['status','Current Status'],['public-project','Public Project']].map(([id,name])=>`<a href="#${id}">${name}</a>`).join('')}</aside><div class="case-copy"><section id="overview"><h2>Overview</h2><p>${project.overview}</p></section><section id="problem"><h2>Problem</h2><p>${project.problem}</p></section><section id="my-role"><h2>My Role</h2><p>${project.contribution}</p></section><section id="work"><h2>What I Worked On</h2>${items(project.work)}</section><section id="functionality"><h2>${project.personal ? 'Key Functionality — Product Concept' : 'Key Functionality'}</h2>${items(project.features)}</section><section id="challenges"><h2>Challenges</h2><p>${project.challenge}</p></section><section id="approach"><h2>Approach</h2><p>${project.approach}</p></section><section id="status"><h2>Outcome / Current Status</h2><p>${project.status}</p></section><section id="public-project"><h2>Public Project</h2>${external(project.url,esc(new URL(project.url).hostname),'public-link')}<p class="ownership-note">${project.personal ? 'BANT is my own product and is currently in development. The demo may change as the MVP evolves.' : confidentiality+' Project branding and assets belong to their respective owners.'}</p></section></div></section><section class="case-next container"><p class="eyebrow">CONTINUE EXPLORING</p><div>${data.projects.filter(p=>p.slug!==project.slug).map(p=>`<a href="${p.slug}.html">${p.name} <span aria-hidden="true">↗</span></a>`).join('')}</div></section>`;
 await writeFile(new URL(`case-studies/${project.slug}.html`, output), layout({ title:`${project.name} Case Study | Enoch Benson`, description:project.summary, path:`case-studies/${project.slug}.html`, body, detail:true }));
}
await writeFile(new URL('robots.txt', output), `User-agent: *\nAllow: /\nSitemap: ${data.origin}/sitemap.xml\n`);
await writeFile(new URL('sitemap.xml', output), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...data.projects.map(p=>`case-studies/${p.slug}.html`)].map(path=>`<url><loc>${data.origin}/${path}</loc></url>`).join('')}</urlset>`);
await writeFile(new URL('.nojekyll', output), '');
console.log('Built home page, five case studies, assets, sitemap and robots.txt.');
